### PR TITLE
Removed image size maximum of 255 px restriction

### PR DESCRIPTION
**Pull request by sakkeerhussain**
Removed image size maximum of 255 px restriction by updating high width and high height command value, rather adding '00' before.

### CODE REVIEW

**Comment by mrashidcit** [comment]
Its Prefectly working.
Thank You @sakkeerhussain 
Thank You very much.

**Comment by sakkeerhussain** [comment]
@mrashidcit you are welcome.

**Comment by ajmalpk23** [comment]
java?

**Comment by sakkeerhussain** [comment]
> I've been using this for a while now, i create a bitmap as receipt and then print it as an image, sometimes when the image is large it won't print entirely and/or won't do that cut command that i added at the end.
> 
> Can anyone confirm? Behavior starts to get flaky after about 2000 pixels height

Not sure.  But with the updates I did, you should ideally should be able to print images of max size 255*255 in height and width.

**Comment by mazenrashed** [comment]
Thanks for the great contribution

**Pull request merged**
