### PR TITLE
create disconnected function for printing callback

### PR DESCRIPTION
**Pull request by danielpsantiago**

### CODE REVIEW

**Comment by mazenrashed** [comment]
Thanks for the pull request,
I will review it at the weekend inshallah,
Regards,

**Comment by danielpsantiago** [comment]
Thanks! 
I needed that change fast, so I had to generate the aar manually while this PR is not merged
Once it's merged, I'll revolve to the actual lib.

Thank you!

**Comment by danielpsantiago** [comment]
Do we have any news on this?

**Comment by mazenrashed** [comment]
Thanks for the great contribution

**Pull request merged**
